### ISSUE TITLE
who is not working 

### ISSUE THREAD

**Issue by superkalt** [asad-boutique/node-bacnet-contrib-extended#1]
![image](https://user-images.githubusercontent.com/44277174/185929404-6dedfe92-adab-4a5e-b7f1-8bcb1a2c63de.png)

![image](https://user-images.githubusercontent.com/44277174/185929225-68c158e7-3953-4c10-a5e1-0b1c99f418fc.png)

there is 1 device in the network

**Comment by asad-boutique** [comment]
hi, Are you running node-red within a docker container??? If yes then discover-devices and read-all-devices nodes would not work properly until you run your docker container in a host network mode on a linux machine, keep in mind that the host network mode is not supported on apple macbooks

**Comment by superkalt** [comment]
yep. i will change that.

**Comment by superkalt** [comment]
![image](https://user-images.githubusercontent.com/44277174/186090415-26b31cdb-550d-424e-823a-81dd6e270585.png)
