### ISSUE TITLE
Write

### ISSUE THREAD

**Issue by vigalent** [asad-boutique/node-bacnet-contrib-extended#4]
Hi. Are there any examples on how to use the 'write-a-value' node?

I tried this in a function module connected to the write node but it does not work

`msg.payload =
{
    objectId: { type: 2, instance: 1 },
    address: "192.168.1.200",
    property: { id: 85 },
    values: [{
        type: 4,
        value: 1
    }],
    options: { priority: 9 }
};
return msg;`

**Comment by cashew22** [comment]
@vigalent The node is just not working because it's not really implemented, i'll have a pull request soon that adds the feature if you still need it
